In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("../../datos_completos.csv")

In [8]:
df.shape

(392, 30)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   nregistro                      392 non-null    int64
 1   nombre                         392 non-null    str
 2   pactivos                       392 non-null    str
 3   labtitular                     392 non-null    str
 4   labcomercializador             392 non-null    str
 5   cn                             392 non-null    int64
 6   dosis                          392 non-null    str
 7   formaFarmaceuticaSimplificada  392 non-null    str
 8   estado_aut                     392 non-null    int64
 9   estado_rev                     39 non-null     float64
 10  viasAdministracion             392 non-null    str
 11  comerc                         392 non-null    bool
 12  receta                         392 non-null    bool
 13  generico                       392 non-null    bool
 14  conduc                         392 non-null    bool
 15  triangulo                      392 non-null    bool
 16  huerfano                       392 non-null    bool
 17  biosimilar                     392 non-null    bool
 18  url_html_ficha_tecnica         392 non-null    str
 19  url_foto_materiales            167 non-null    str
 20  num_registros_atc              392 non-null    int64
 21  num_principios_activos         392 non-null    int64
 22  n_palabras                     392 non-null    int64
 23  n_tablas                       392 non-null    int64
 24  n_graves                       392 non-null    int64
 25  estado_nomenclator             307 non-null    str
 26  pvp_iva                        307 non-null    float64
 27  precio_referencia              276 non-null    float64
 28  tratamiento_larga_duracion     307 non-null    str
 29  especial_control_medico        307 non-null    str
dtypes: bool(7), float64(3), int64(8), str(12)
memory usage: 73.2 KB

In [10]:
df.head()

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,formaFarmaceuticaSimplificada,estado_aut,estado_rev,...,num_registros_atc,num_principios_activos,n_palabras,n_tablas,n_graves,estado_nomenclator,pvp_iva,precio_referencia,tratamiento_larga_duracion,especial_control_medico
0,52105,ACTOCORTINA 373 mg POLVO PARA SOLUCIÓN INYECTABLE,HIDROCORTISONA FOSFATO SODIO,Cheplapharm Arzneimittel Gmbh,Laboratorios Rubio S.A.,606558,373 MG,INYECTABLE,128905200000,NaN,...,3,1,1293,1,5,NaN,NaN,NaN,NaN,NaN
1,80248,AIRFLUSAL FORSPIRO 50 MICROGRAMOS/250 MICROGRA...,"FLUTICASONA PROPIONATO, SALMETEROL XINAFOATO",Sandoz Farmaceutica S.A.,Sandoz Farmaceutica S.A.,707896,50 microgramos/250 microgramos,INHALACIÓN PULMONAR,1447110000000,NaN,...,3,2,1543,5,16,ALTA,41.28,41.28,NO,NO
2,80249,AIRFLUSAL FORSPIRO 50 MICROGRAMOS/500 MICROGRA...,"SALMETEROL XINAFOATO, FLUTICASONA PROPIONATO",Sandoz Farmaceutica S.A.,Sandoz Farmaceutica S.A.,707904,50 microgramos/500 microgramos,INHALACIÓN PULMONAR,1447110000000,NaN,...,3,2,1543,5,16,ALTA,41.28,41.28,NO,NO
3,62839,ANASMA ACCUHALER 50 microgramos/100 microgramo...,"FLUTICASONA PROPIONATO, SALMETEROL XINAFOATO",Glaxosmithkline S.A.,Glaxosmithkline S.A.,842898,"0,1 mg / 0,05 mg",INHALACIÓN PULMONAR,945644400000,NaN,...,3,2,1435,7,20,ALTA,41.28,41.28,NO,NO
4,62840,ANASMA ACCUHALER 50 microgramos/250 microgramo...,"FLUTICASONA PROPIONATO, SALMETEROL XINAFOATO",Glaxosmithkline S.A.,Glaxosmithkline S.A.,700543,"0,25 mg / 0,05 mg",INHALACIÓN PULMONAR,945644400000,NaN,...,3,2,1436,7,20,ALTA,41.28,41.28,NO,NO

In [11]:
df.tail()

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,formaFarmaceuticaSimplificada,estado_aut,estado_rev,...,num_registros_atc,num_principios_activos,n_palabras,n_tablas,n_graves,estado_nomenclator,pvp_iva,precio_referencia,tratamiento_larga_duracion,especial_control_medico
387,66408,VENTILASTIN NOVOLIZER 100 microgramos/DOSIS PO...,SALBUTAMOL SULFATO,Mylan Ire Healthcare Limited,Mylan Pharmaceuticals S.L.,656705,100 mcg salbutamol sulfato,INHALACIÓN PULMONAR,1098741600000,1.703672e+12,...,3,1,725,1,10,NaN,NaN,NaN,NaN,NaN
388,52404,VENTOALDO 100 mcg/DOSIS SUSPENSION PARA INHALA...,SALBUTAMOL SULFATO,Laboratorio Aldo Union S.L.,Laboratorio Aldo Union S.L.,652530,"0,2400 g",INHALACIÓN PULMONAR,136591200000,NaN,...,3,1,561,0,11,ALTA,6.21,6.21,SI,NO
389,55497,VENTODUO 100 MICROGRAMOS/50 MICROGRAMOS/PULSAC...,"SALBUTAMOL SULFATO, BECLOMETASONA DIPROPIONATO",Laboratorio Aldo Union S.L.,Laboratorio Aldo Union S.L.,700656,50 microgramos/100 microgramos,INHALACIÓN PULMONAR,357516000000,NaN,...,3,2,1104,1,7,ALTA,9.59,NaN,NO,NO
390,53931,"VENTOLIN 4 mg, COMPRIMIDOS",SALBUTAMOL,Glaxosmithkline S.A.,Glaxosmithkline S.A.,845735,4 mg salbutamol,COMPRIMIDO,244508400000,1.699461e+12,...,3,1,678,0,8,BAJA GENERAL,2.81,2.81,SI,NO
391,5319002,XOLAIR 150 mg POLVO Y DISOLVENTE PARA SOLUCION...,OMALIZUMAB,Novartis Europharm Limited,Novartis Farmaceutica S.A.,652563,150 mg,INYECTABLE,1131577200000,NaN,...,3,1,755,9,24,NaN,NaN,NaN,NaN,NaN